export type PvIntakeStatus =
  | 'build_done'
  | 'whatsapp_intake_open'
  | 'ai_structuring'
  | 'review_missing_data'
  | 'pre_registration_and_mastr'
  | 'final_notification'
  | 'closed';

export type AttachmentType = 'image' | 'voice' | 'text';

export type AttachmentClassification =
  | 'meter'
  | 'meter_reading'
  | 'inverter_label'
  | 'battery_label'
  | 'switchboard'
  | 'roof'
  | 'other';

export type AttachmentExtracted = {
  fields: Record<string, unknown>;
  confidence: number;
};

export type Attachment = {
  id: string;
  type: AttachmentType;
  url?: string;
  transcript?: string;
  text?: string;
  takenAt: string;
  senderName: string;
  classification?: AttachmentClassification;
  extracted?: AttachmentExtracted;
};

export type MeterReading = {
  kind: 'import' | 'export';
  valueKwh: number;
  takenAt: string;
};

export type PvModule = {
  brand: string;
  model: string;
  watt: number;
  count: number;
};

export type PvInverter = {
  brand: 'FoxESS';
  model: string;
  powerKw: number;
  serialNumber: string;
};

export type PvStorage = {
  brand: 'FoxESS';
  model: string;
  capacityKwh: number;
  serialNumber: string;
};

export type PvOperator = {
  name?: string | null;
  email?: string | null;
  phone?: string | null;
};

export type PvChecklistItem = {
  id: string;
  title: string;
  done: boolean;
  severity: 'info' | 'required';
  autoGenerated: boolean;
};

export type PvDocument = {
  name: string;
  url?: string;
  createdAt: string;
};

export type PvExtractedData = {
  meterNumber?: string | null;
  meterReadings?: MeterReading[];
  pv: {
    generatorKwp?: number | null;
    module?: PvModule | null;
    inverter?: PvInverter | null;
    storage?: PvStorage | null;
  };
  operator: PvOperator;
};

export type PvCase = {
  id: string;
  createdAt: string;
  updatedAt: string;
  customerName: string;
  address: string;
  netzbetreiber: 'stromnetz_berlin' | 'edis';
  status: PvIntakeStatus;
  messages: Attachment[];
  extractedData: PvExtractedData;
  checklist: PvChecklistItem[];
  documents: {
    preReg?: PvDocument[];
    mastr?: PvDocument[];
    final?: PvDocument[];
  };
};
