import type { Attachment, PvCase, PvChecklistItem } from '../types';

const createId = () =>
  typeof crypto !== 'undefined' && crypto.randomUUID
    ? crypto.randomUUID()
    : `pv-${Date.now()}-${Math.random().toString(16).slice(2)}`;

const createAttachment = (data: Partial<Attachment> & Pick<Attachment, 'type'>): Attachment => ({
  id: createId(),
  takenAt: data.takenAt ?? new Date().toISOString(),
  senderName: data.senderName ?? 'Technician',
  ...data,
});

const createChecklist = (items: Array<Partial<PvChecklistItem> & { title: string }>) =>
  items.map((item) => ({
    id: createId(),
    title: item.title,
    done: item.done ?? false,
    severity: item.severity ?? 'info',
    autoGenerated: item.autoGenerated ?? true,
  }));

export const mockPvCases: PvCase[] = [
  {
    id: createId(),
    createdAt: '2026-01-05T08:10:00.000Z',
    updatedAt: '2026-01-12T14:40:00.000Z',
    customerName: 'Lena Mueller',
    address: 'Kantstrasse 15, 10623 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'whatsapp_intake_open',
    messages: [
      createAttachment({
        type: 'text',
        text: 'Build done. Meter photo and inverter label coming soon.',
        senderName: 'Alex',
        takenAt: '2026-01-12T14:35:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-meter-1/520/360',
        classification: 'meter',
        senderName: 'Vasya',
        takenAt: '2026-01-12T14:38:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-roof-1/520/360',
        classification: 'roof',
        senderName: 'Vasya',
        takenAt: '2026-01-12T14:39:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: null,
      meterReadings: [],
      pv: {
        generatorKwp: 9.8,
        module: { brand: 'Trina', model: 'Vertex S', watt: 425, count: 23 },
        inverter: null,
        storage: null,
      },
      operator: {
        name: null,
        email: null,
        phone: null,
      },
    },
    checklist: createChecklist([
      { title: 'Collect inverter label photo', severity: 'required' },
      { title: 'Verify meter number from photo', severity: 'required' },
      { title: 'Confirm operator contact details', severity: 'required' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2026-01-03T09:20:00.000Z',
    updatedAt: '2026-01-14T10:15:00.000Z',
    customerName: 'Rico Lehmann',
    address: 'Prenzlauer Allee 44, 10405 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'ai_structuring',
    messages: [
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-inverter-1/520/360',
        senderName: 'Dima',
        takenAt: '2026-01-14T09:50:00.000Z',
      }),
      createAttachment({
        type: 'voice',
        transcript: 'FoxESS H3-10.0, serial starts with FXH3, storage ECS2900.',
        senderName: 'Dima',
        takenAt: '2026-01-14T09:55:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-switchboard-1/520/360',
        senderName: 'Dima',
        takenAt: '2026-01-14T09:58:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: null,
      pv: {
        generatorKwp: null,
        module: null,
        inverter: null,
        storage: null,
      },
      operator: {
        name: 'Rico Lehmann',
        email: 'rico.lehmann@example.de',
        phone: '+49 30 123456',
      },
    },
    checklist: createChecklist([
      { title: 'Await AI extraction', severity: 'info' },
      { title: 'Confirm generator kWp from build docs', severity: 'required' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2025-12-28T12:05:00.000Z',
    updatedAt: '2026-01-10T11:40:00.000Z',
    customerName: 'Simona Krueger',
    address: 'Gneisenaustrasse 12, 10961 Berlin',
    netzbetreiber: 'edis',
    status: 'review_missing_data',
    messages: [
      createAttachment({
        type: 'text',
        text: 'Battery label photo attached.',
        senderName: 'Alex',
        takenAt: '2026-01-10T11:20:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-battery-1/520/360',
        classification: 'battery_label',
        senderName: 'Vasya',
        takenAt: '2026-01-10T11:22:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-meter-2/520/360',
        classification: 'meter',
        senderName: 'Vasya',
        takenAt: '2026-01-10T11:25:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '1EZ1234567',
      meterReadings: [
        { kind: 'import', valueKwh: 12840, takenAt: '2026-01-10T11:25:00.000Z' },
      ],
      pv: {
        generatorKwp: 7.2,
        module: { brand: 'JA Solar', model: 'JAM54', watt: 410, count: 18 },
        inverter: { brand: 'FoxESS', model: 'H1-6.0', powerKw: 6, serialNumber: 'FXH1-6-2214' },
        storage: { brand: 'FoxESS', model: 'ECS2900', capacityKwh: 5.8, serialNumber: 'FXECS-2233' },
      },
      operator: {
        name: 'Simona Krueger',
        email: null,
        phone: '+49 152 334455',
      },
    },
    checklist: createChecklist([
      { title: 'Missing operator email', severity: 'required' },
      { title: 'Confirm export meter reading', severity: 'required' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2025-12-22T07:55:00.000Z',
    updatedAt: '2026-01-09T16:20:00.000Z',
    customerName: 'Holger Becker',
    address: 'Friedrichstrasse 104, 10117 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'pre_registration_and_mastr',
    messages: [
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-inverter-2/520/360',
        classification: 'inverter_label',
        senderName: 'Dima',
        takenAt: '2026-01-08T14:10:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-meter-3/520/360',
        classification: 'meter_reading',
        senderName: 'Dima',
        takenAt: '2026-01-08T14:12:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '2EZ9876543',
      meterReadings: [
        { kind: 'import', valueKwh: 9920, takenAt: '2026-01-08T14:12:00.000Z' },
        { kind: 'export', valueKwh: 120, takenAt: '2026-01-08T14:12:00.000Z' },
      ],
      pv: {
        generatorKwp: 12.3,
        module: { brand: 'QCells', model: 'Q.PEAK', watt: 410, count: 30 },
        inverter: { brand: 'FoxESS', model: 'H3-12.0', powerKw: 12, serialNumber: 'FXH3-12-8891' },
        storage: { brand: 'FoxESS', model: 'ECS4300', capacityKwh: 8.6, serialNumber: 'FXECS-4311' },
      },
      operator: {
        name: 'Holger Becker',
        email: 'holger.becker@example.de',
        phone: '+49 30 998877',
      },
    },
    checklist: createChecklist([
      { title: 'Generate pre-registration PDF', severity: 'info' },
      { title: 'Submit MaStR entry', severity: 'info' },
    ]),
    documents: {
      preReg: [{ name: 'Pre-registration summary', createdAt: '2026-01-09T15:00:00.000Z' }],
    },
  },
  {
    id: createId(),
    createdAt: '2025-12-20T09:40:00.000Z',
    updatedAt: '2026-01-08T13:10:00.000Z',
    customerName: 'Mira Yilmaz',
    address: 'Sonnenallee 77, 12045 Berlin',
    netzbetreiber: 'edis',
    status: 'final_notification',
    messages: [
      createAttachment({
        type: 'text',
        text: 'Commissioning done. Final documents pending.',
        senderName: 'Alex',
        takenAt: '2026-01-08T12:55:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '3EZ1209987',
      meterReadings: [
        { kind: 'import', valueKwh: 10870, takenAt: '2026-01-07T10:05:00.000Z' },
      ],
      pv: {
        generatorKwp: 8.4,
        module: { brand: 'LONGi', model: 'Hi-MO', watt: 420, count: 20 },
        inverter: { brand: 'FoxESS', model: 'H1-8.0', powerKw: 8, serialNumber: 'FXH1-8-3377' },
        storage: { brand: 'FoxESS', model: 'ECS2900', capacityKwh: 5.8, serialNumber: 'FXECS-2299' },
      },
      operator: {
        name: 'Mira Yilmaz',
        email: 'mira.yilmaz@example.de',
        phone: '+49 151 445566',
      },
    },
    checklist: createChecklist([
      { title: 'Upload commissioning protocol', severity: 'required' },
      { title: 'Send final notification to DSO', severity: 'required' },
    ]),
    documents: {
      mastr: [{ name: 'MaStR submission', createdAt: '2026-01-07T11:00:00.000Z' }],
    },
  },
  {
    id: createId(),
    createdAt: '2025-12-19T08:15:00.000Z',
    updatedAt: '2026-01-06T09:30:00.000Z',
    customerName: 'Tim Schneider',
    address: 'Hauptstrasse 30, 15831 Blankenfelde',
    netzbetreiber: 'edis',
    status: 'build_done',
    messages: [
      createAttachment({
        type: 'text',
        text: 'Build finished, waiting for WhatsApp intake.',
        senderName: 'Alex',
        takenAt: '2026-01-06T09:20:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: null,
      pv: { generatorKwp: null, module: null, inverter: null, storage: null },
      operator: { name: null, email: null, phone: null },
    },
    checklist: createChecklist([
      { title: 'Start WhatsApp intake', severity: 'required' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2025-12-15T10:05:00.000Z',
    updatedAt: '2026-01-05T16:40:00.000Z',
    customerName: 'Petra Hoffmann',
    address: 'Schlossstrasse 22, 12163 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'pre_registration_and_mastr',
    messages: [
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-meter-4/520/360',
        classification: 'meter_reading',
        senderName: 'Vasya',
        takenAt: '2026-01-05T15:50:00.000Z',
      }),
      createAttachment({
        type: 'voice',
        transcript: 'Inverter FoxESS H3-8, serial FXH3-8-4022.',
        senderName: 'Vasya',
        takenAt: '2026-01-05T15:55:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '5EZ5667788',
      meterReadings: [{ kind: 'import', valueKwh: 5400, takenAt: '2026-01-05T15:50:00.000Z' }],
      pv: {
        generatorKwp: 6.8,
        module: { brand: 'QCells', model: 'Q.PEAK', watt: 400, count: 17 },
        inverter: { brand: 'FoxESS', model: 'H3-8', powerKw: 8, serialNumber: 'FXH3-8-4022' },
        storage: null,
      },
      operator: { name: 'Petra Hoffmann', email: 'petra.h@example.de', phone: '+49 30 778811' },
    },
    checklist: createChecklist([
      { title: 'Submit pre-registration on portal', severity: 'info' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2025-12-10T11:30:00.000Z',
    updatedAt: '2026-01-04T11:00:00.000Z',
    customerName: 'Jonas Ritter',
    address: 'Karl-Marx-Strasse 188, 12043 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'review_missing_data',
    messages: [
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-inverter-3/520/360',
        senderName: 'Dima',
        takenAt: '2026-01-04T10:30:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-roof-2/520/360',
        senderName: 'Dima',
        takenAt: '2026-01-04T10:35:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: null,
      pv: {
        generatorKwp: null,
        module: { brand: 'Trina', model: 'Vertex S', watt: 425, count: 20 },
        inverter: { brand: 'FoxESS', model: 'H1-6.0', powerKw: 6, serialNumber: '' },
        storage: null,
      },
      operator: { name: 'Jonas Ritter', email: null, phone: '+49 30 556677' },
    },
    checklist: createChecklist([
      { title: 'Missing meter photo', severity: 'required' },
      { title: 'Missing inverter serial number', severity: 'required' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2025-12-06T13:15:00.000Z',
    updatedAt: '2026-01-03T12:05:00.000Z',
    customerName: 'Anja Scholz',
    address: 'Berliner Strasse 9, 14532 Kleinmachnow',
    netzbetreiber: 'edis',
    status: 'final_notification',
    messages: [
      createAttachment({
        type: 'text',
        text: 'All docs ready, final notification next.',
        senderName: 'Alex',
        takenAt: '2026-01-03T12:00:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '9EZ6677111',
      meterReadings: [{ kind: 'import', valueKwh: 7800, takenAt: '2026-01-02T09:50:00.000Z' }],
      pv: {
        generatorKwp: 10.2,
        module: { brand: 'LONGi', model: 'Hi-MO', watt: 420, count: 24 },
        inverter: { brand: 'FoxESS', model: 'H3-10', powerKw: 10, serialNumber: 'FXH3-10-9021' },
        storage: { brand: 'FoxESS', model: 'ECS4300', capacityKwh: 8.6, serialNumber: 'FXECS-4302' },
      },
      operator: { name: 'Anja Scholz', email: 'anja.s@example.de', phone: '+49 30 223344' },
    },
    checklist: createChecklist([
      { title: 'Send final report to DSO', severity: 'required' },
      { title: 'Archive commissioning docs', severity: 'info' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2025-12-01T08:25:00.000Z',
    updatedAt: '2026-01-02T09:10:00.000Z',
    customerName: 'Sophie Wagner',
    address: 'Koenigstrasse 8, 16816 Neuruppin',
    netzbetreiber: 'edis',
    status: 'closed',
    messages: [
      createAttachment({
        type: 'text',
        text: 'Case closed. All notifications completed.',
        senderName: 'Alex',
        takenAt: '2026-01-02T09:00:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '7EZ1010101',
      meterReadings: [{ kind: 'import', valueKwh: 13200, takenAt: '2026-01-01T12:00:00.000Z' }],
      pv: {
        generatorKwp: 13.2,
        module: { brand: 'QCells', model: 'Q.PEAK', watt: 400, count: 33 },
        inverter: { brand: 'FoxESS', model: 'H3-12.0', powerKw: 12, serialNumber: 'FXH3-12-7001' },
        storage: { brand: 'FoxESS', model: 'ECS4300', capacityKwh: 8.6, serialNumber: 'FXECS-4309' },
      },
      operator: { name: 'Sophie Wagner', email: 's.wagner@example.de', phone: '+49 30 665544' },
    },
    checklist: createChecklist([
      { title: 'Final notification sent', severity: 'info', done: true },
    ]),
    documents: {
      final: [{ name: 'Final notification PDF', createdAt: '2026-01-01T10:00:00.000Z' }],
    },
  },
  {
    id: createId(),
    createdAt: '2026-01-07T08:30:00.000Z',
    updatedAt: '2026-01-13T15:20:00.000Z',
    customerName: 'Denis Novak',
    address: 'Bismarckstrasse 65, 10627 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'whatsapp_intake_open',
    messages: [
      createAttachment({
        type: 'voice',
        transcript: 'Need to send meter photo and export reading.',
        senderName: 'Vasya',
        takenAt: '2026-01-13T15:10:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-switchboard-2/520/360',
        senderName: 'Vasya',
        takenAt: '2026-01-13T15:12:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: null,
      pv: { generatorKwp: 5.4, module: null, inverter: null, storage: null },
      operator: { name: 'Denis Novak', email: null, phone: '+49 30 223311' },
    },
    checklist: createChecklist([
      { title: 'Request meter photo', severity: 'required' },
      { title: 'Capture inverter label', severity: 'required' },
    ]),
    documents: {},
  },
  {
    id: createId(),
    createdAt: '2026-01-08T10:40:00.000Z',
    updatedAt: '2026-01-14T08:40:00.000Z',
    customerName: 'Greta Schulz',
    address: 'Auguststrasse 12, 10117 Berlin',
    netzbetreiber: 'stromnetz_berlin',
    status: 'review_missing_data',
    messages: [
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-meter-5/520/360',
        senderName: 'Dima',
        takenAt: '2026-01-14T08:30:00.000Z',
      }),
      createAttachment({
        type: 'image',
        url: 'https://picsum.photos/seed/pv-inverter-4/520/360',
        senderName: 'Dima',
        takenAt: '2026-01-14T08:35:00.000Z',
      }),
    ],
    extractedData: {
      meterNumber: '1EZ3322445',
      meterReadings: [],
      pv: {
        generatorKwp: 7.6,
        module: { brand: 'LONGi', model: 'Hi-MO', watt: 420, count: 18 },
        inverter: { brand: 'FoxESS', model: 'H1-6.0', powerKw: 6, serialNumber: 'FXH1-6-7711' },
        storage: null,
      },
      operator: { name: 'Greta Schulz', email: 'g.schulz@example.de', phone: null },
    },
    checklist: createChecklist([
      { title: 'Export meter reading missing', severity: 'required' },
      { title: 'Confirm operator phone', severity: 'required' },
    ]),
    documents: {},
  },
];
